[versions]
paper-api = "1.21.4-R0.1-SNAPSHOT"
lombok = "1.18.34"
commandapi = "11.1.0"
configlib = "4.6.0"
shadow = "8.3.0"
run-paper = "2.3.0"
packetevents = "2.11.1"
entitylib = "2.4.11"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
commandapi-shade = { group = "dev.jorel", name = "commandapi-paper-shade", version.ref = "commandapi" }
configlib-yaml = { group = "de.exlll", name = "configlib-yaml", version.ref = "configlib" }
configlib-paper = { group = "de.exlll", name = "configlib-paper", version.ref = "configlib" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
entitylib = { module = "com.github.Tofaa2.EntityLib:spigot", version.ref = "entitylib"}

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }